### ISSUE TITLE
Hide License in menu bar not working

### ISSUE THREAD

**Issue by bsun0802** [mtn/cocoa-eh-hugo-theme#101]
Hi,

Sorry to bother you again~
I noticed that this theme is intended to hide the LICENSE button when added a license.md, instead click the @copyright in the footer will direct to the license.md in content.

But for some reason this feature is disabled, so there will be a LICNSE button in menu.bar if there is a `content/license.md`. I checked `layouts/partials` but I can't figure out where. 

I think it should be in `layouts/partials/header.html`, but as I rest the header.html as the original one, then LICENSE button still there. But the @copyright in footer works well, it shows `content/license.md`

**Comment by mtn** [comment]
Sorry, I'm not really following what you mean. Could you maybe include pictures of what you think is wrong? Thanks!

**Comment by bsun0802** [comment]
please answer this question instead: where should I put the license file for the site, should it be a license.md file?

**Comment by mtn** [comment]
If you haven't done so already, set the title of the license file to `"License"` (case-sensitive). This should be what matters, rather than the name of the file itself.

Let me know if you run into any further issues!

**Comment by mtn** [comment]
The relevant code:

```html
                    {{ range where .Site.RegularPages "Section" ""}}
                        {{ if and (ne .Title "License") (ne .Title "Home")}}
                            <li><a href="{{ .Permalink }}">{{ .Title }}</a></li>
                        {{ end }}
                    {{ end }}
```

**Comment by bsun0802** [comment]
Thanks, that solves my problem and helps my understanding!
