### ISSUE TITLE
can't enable Disqus comment 

### ISSUE THREAD

**Issue by bsun0802** [mtn/cocoa-eh-hugo-theme#102]
Hi,

After a bit experiments, I think the code that enable disqus is in `cocoa-eh/layouts/partials/blog_single.html`. The original code as shown below is not working.

```html
            {{ if .Site.Params.disqusShortname }}
            <div class="disqus">
                {{ template "_internal/disqus.html" . }}
            </div>
            {{ end }}
```

Instead, if I add a single line ` {{ template "_internal/disqus.html" . }}` after the code chunk above.
It becomes

```html
            {{ if .Site.Params.disqusShortname }}
            <div class="disqus">
                {{ template "_internal/disqus.html" . }}
            </div>
            {{ end }}
     
            {{ template "_internal/disqus.html" . }}  # this line added only

            {{ if .Site.Params.issoHost }}
            <div class="isso" id="isso-thread"></div>
            <script
                data-isso="//{{ .Site.Params.issoHost }}/"
                data-isso-css="true"
                data-isso-lang="{{ .Site.LanguageCode }}"
                src="//{{ .Site.Params.issoHost }}/js/embed.min.js"
            ></script>
            {{ end }}
```

And the disqus works.(and this should confirm that I set the disqusShortname = @my-short-name correctly in `config.toml`, since disqus displayed successfully in my site host) 

But I don't know why? Tho I know nothing about html I think the original code should also work.

**Comment by bsun0802** [comment]
Ohhhh... I see. In this theme disqusShortname should be placed in [params] 😢 
it is a little bit strange, but works for me **if only if** disqusShortname was set on top of config.toml and under the [params] in config.toml.

**Comment by mtn** [comment]
Glad you were able to figure that out. You might find the wiki helpful -- for example, [this page](https://github.com/mtn/cocoa-eh-hugo-theme/wiki/Comments) is about comments. I guess the disqus setup wasn't explained as well as some of the others, so I've updated it.

Also, in general, whenever you see something referred to as `Site.params.*`, it'll be defined by the user in the `[params]` section of the config file.

Let me know if you have any further questions!
