### ISSUE TITLE
Option to disable reading time on blog posts?

### ISSUE THREAD

**Issue by mfherman** [mtn/cocoa-eh-hugo-theme#107]
Thanks for the great theme! 

I'm wondering if there is a way to disable the reading time display on blog posts. It looks like other Hugo themes have this option that can be set in `config.toml` but I'm not able to find such an option on this theme.

**Comment by mtn** [comment]
There currently isn't an option, but I can easily add it. It'll be enabled by default, and you'd set a value in your config file to disable it.

I'll leave this issue open until it's finished.

**Comment by mfherman** [comment]
Thanks!

**Comment by mtn** [comment]
@mfherman This is done. You can set `noreadingtime = true` under `[params]` in your config file now.

Feel free to ping me if anything doesn't work as you expected!

**Comment by mfherman** [comment]
Works perfectly -- thanks again!

**Comment by unsungNovelty** [comment]
@mtn - Thanks a lot for the amazing theme!

Curious to know how to enable the reading time which I am unable to figure out. Didn't open a new ticket as this could be one stop for people who want to disable and enable the reading time. Appreciate your time on this.

Let me know if this warrants a new ticket! :)

**Comment by mtn** [comment]
@unsungNovelty The relevant code is [here](https://github.com/mtn/cocoa-eh-hugo-theme/blob/55588aeba1316ccb1fde8a732babae3e11ffe228/layouts/partials/blog_single.html#L23).  Do you have `noreadingtime` set to true under `[params]` in your config file?

**Comment by unsungNovelty** [comment]
I figured that it is automatic in "blog" section. Although I didn't find a fix for new listed section @mtn.

>  Do you have noreadingtime set to true under [params] in your config file?

It is `false` @mtn
