### ISSUE TITLE
Redundant language specification?

### ISSUE THREAD

**Issue by Hjdskes** [mtn/cocoa-eh-hugo-theme#12]
Hi,

I was going through this theme's `config.toml` and noticed you require setting an extra `lang` parameter. Apparantly, this is used in [partials/header.html:6](https://github.com/fuegowolf/cocoa-eh-hugo-theme/blob/master/layouts/partials/header.html#L6). Isn't this redundant? On line 2 in the same file, the language is already set. If it is not redundant, then why don't you reuse `.Site.LanguageCode`?

Thanks!

**Comment by fuegoio** [comment]
Hi !

This `lang` parameter is a bit redundant yes, I never saw this. In fact, the `lang` parameter on the `body` is not useful at all.

Fixed by 74ac69fb6a90b0fe197a78d6ea0c067f1ad4bc51

**Comment by Hjdskes** [comment]
Cheers, thanks!
