### ISSUE TITLE
The section gets reorganised based on the last post of a list-section.

### ISSUE THREAD

**Issue by unsungNovelty** [mtn/cocoa-eh-hugo-theme#140]
Hi,

First of all, thanks for the amazing theme. This is not just well built but also moderately well documented unlike a lot of other themes.

### The issue:

When I add a new post to "blog" section, blog gets organised to the first section. But when I add a post to another list section, that gets reorganised as the first section of the website. 

_**Section BEFORE adding a new post to "list-section" which is a section that lists posts**_
![image](https://user-images.githubusercontent.com/11845908/64122538-91cba200-cdbf-11e9-95c5-17fb4c350cd5.png)

_**Section AFTER adding a new post to "list-section" which is a section that lists posts**_
![image](https://user-images.githubusercontent.com/11845908/64122790-33eb8a00-cdc0-11e9-884f-a28180bf9607.png)

@mtn Is this an expected behaviour? If yes, how can I keep the section arranging constant? Really appreciate your time on this. :slightly_smiling_face:

**Comment by mtn** [comment]
I'll have to check the implementation to be sure, but that should be easy enough to change and I see no reason to not support the behavior you're suggesting. I can make a PR at some point over the next few days, or if you want to make it yourself I'm happy to help.

**Comment by unsungNovelty** [comment]
:ok_hand: 

I just used the "blog" instead of multiple listed-sections and is thinking about using the tags to organise my posts as a work-around although I still didn't find the solution for the issue (also, that is better than multiple listed-section I feel.). The last updated list-section seems to get organised as first among the sections. 

> if you want to make it yourself I'm happy to help.

I really would like to but am on quite a stretch at the moment. Lemme know if you want me to close the issue. And thanks a lot for taking the time to reply. Appreciate it.

**Comment by unsungNovelty** [comment]
Closing this.
