### ISSUE TITLE
Error with <absURL>

### ISSUE THREAD

**Issue by vncastanheira** [mtn/cocoa-eh-hugo-theme#18]
I tried to run `hugo -t cocoa-eh` in a vanilla hugo website, but keep getting the following error message:

`ERROR 2017/03/12 23:15:42 theme/partials/header.html template: theme/partials/header.html:14:88: executing "theme/partials/header.html" at <absURL>: wrong number of args for absURL: want 1
 got 0`

**Comment by fuegoio** [comment]
Hi !
This is because you didn't specify a `.Site.Params.logofile`. In the params, you should add this value, or maybe replace this line in the theme if you don't want a logo.

**Comment by vncastanheira** [comment]
Gonna try again.

Thanks!
