### ISSUE TITLE
Set ordered list type to numbered

### ISSUE THREAD

**Issue by curreta** [mtn/cocoa-eh-hugo-theme#19]
Ordered lists are currently using the `list-style-type: disc` which prevents a numbered list from displaying.

When using markdown: 

```
1. hi
2. hello
3. hola
```

- [ ] The above markdown shows as numbered list and not disc type

**Comment by fuegoio** [comment]
Hi !

Thanks for the issue, it is resolved with commit 2e4facb7d5a8dc432e4c474d6eed3ee001a06e5c and is in the v0.9.1 !
