### ISSUE TITLE
"Blog" and Site "Title" are duplicated

### ISSUE THREAD

**Issue by Naata** [mtn/cocoa-eh-hugo-theme#2]
Please look at screenshots below.
Issue can be seen on demo page: http://themes.gohugo.io/theme/cocoa-eh-hugo-theme/

![duplicate_blog](https://cloud.githubusercontent.com/assets/3140296/21742938/19720626-d4f9-11e6-8963-009de6826c4a.PNG)
![duplicate_title](https://cloud.githubusercontent.com/assets/3140296/21742939/197208d8-d4f9-11e6-89f5-b8415f274843.PNG)

**Comment by fuegoio** [comment]
Mhhh I see. Thank you ! I will investigate.

**Comment by Naata** [comment]
It seems that line 28 in **header.html**:
`{{ if ne .Title "Home"}}` 

attaches everything to header. I managed to fix it on my site, by changing this line to:
`{{ if and (ne .Title "Home") (ne .Title "Blog") (ne .Title .Site.Title) }}`

I'll submit pull request for it in couple of minutes.

**Comment by fuegoio** [comment]
There is too many links that's weird. Not only the Blog and Title ones, but Categories and tags too. I think it is because there are too many articles without a Section, and I don't have those in my exampleSite.

**Comment by Naata** [comment]
It looks like these:
![image](https://cloud.githubusercontent.com/assets/3140296/21743071/18b17a30-d4fb-11e6-9960-272aae0d25c1.png)

are some sort of "tags" or "categories" of blog posts. If you click them, you're redirected to site that doesn't have them in header:
![image](https://cloud.githubusercontent.com/assets/3140296/21743087/5be7667a-d4fb-11e6-9898-9dab5e287d7f.png)

**Comment by fuegoio** [comment]
When you click on a "extra" link there is an old version of the theme. I think the cache has not been properly cleared on the theme showcase.

**Comment by ghost** [comment]
I have this bug, too. Even when I'm using your provided exampleSite, @fuegowolf.
See also the GoHugo Demo page of your theme: http://themes.gohugo.io/theme/cocoa-eh-hugo-theme/. There is also the bug.

**Comment by fuegoio** [comment]
I really don't see why this is occuring with my theme. Were you using it before the v0.5 release ? Which version of hugo are you using ? This seems to be a problem of cache I think.

**Comment by Naata** [comment]
Latest Hugo, and latest theme (fresh checkout from git) in my case.

**Comment by fuegoio** [comment]
@Naata Are you sure your pull request resolve the bug for everyone ? This will not clear tags for example I think.

**Comment by Naata** [comment]
It definitely solved problem for me :) It fixes duplicated "blog" and "title". But I'm not familliar enough with Hugo Themes and your template to solve problem with categories being displayed in header.

**Comment by ghost** [comment]
@fuegowolf 
I'm using the latest version of your theme and Hugo.
I tried your exampleSite and several new websites, it's always the same.

@Naata 
I changed my header.html-file in order to apply your changes, however "Categories" and all of the tags are still there. I removed them from the content files and now I get "Blog projects About Projects".

**Comment by fuegoio** [comment]
As said in the PR #5 I wasn't using the last version of Hugo which has changed the pages in .Site.Pages to all pages in the blog. Resolved now :)
