### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by scottf** [mtn/cocoa-eh-hugo-theme#26]
I do a lot of code samples in my blog. go, command shell, html, java, json, etc. I'm finding that the syntax highlighting isn't what I need. How can I change the highlighting? Is there a part of the theme I need to change or some css. Sorry for this nube-ish question

**Comment by fuegoio** [comment]
Hi !

You can change the highlighting in the theme directly with another JS framework if you want, or something with a back end. In the files `layouts/partials/header_includes.html` and `layouts/partials/footer_scripts.html` you can find how HighlightJS is imported, just delete it and replace it by your choice !

See ya !
