### ISSUE TITLE
Syntax highlighting for more languages

### ISSUE THREAD

**Issue by torkleyy** [mtn/cocoa-eh-hugo-theme#31]
First of all, thank you so much for building this theme, really love how clean and simple it is.

I'm trying to show Rust source code, however I'm not quite sure how to get syntax highlighting. I guess this theme only includes `highlightjs` for a small number of languages.

Would you want to have support for more languages or could you please explain what steps are needed to replace `highlight.min.js` with a custom one?

**Comment by fuegoio** [comment]
Hi !

Thanks you ! The commit 87d4c9e1f975fc603c93179a4ee7d8ee1e824f53 improves this, I've added more languages which seem important to me even if the file is bigger (use gzip !), and **Rust** is one of them. This commit will be in a important release really soon, but you can take the `dev` branch if you want, it's working.

If there is a language you need, don't bother modifying the theme and all pages, just add this (for example _golang_) : 

```
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/languages/go.min.js"></script>
```

In your post markdown, it will be translated as HTML and then enable the highlight for your language.

If the language recognition isn't great, force it with : 

```
<pre><code class="html">...</code></pre>
```

Hope that helps ! See ya !

**Comment by torkleyy** [comment]
@fuegowolf Great, it works now! Thanks!
