### ISSUE TITLE
Add commento support?

### ISSUE THREAD

**Issue by seemethere** [mtn/cocoa-eh-hugo-theme#34]
Came across a cool project today that is basically a lightweight, non-tracking, disqus called [commento](https://github.com/adtac/commento).

It'd be cool if this theme got commento support.

I'll see if I can get around to submitting a PR for this in the next couple of days.

**Comment by fuegoio** [comment]
Hi !

Thanks for the idea, the project looks really good ! I can help you on your PR if you want :)

**Comment by mtn** [comment]
@seemethere I guess it's more than a year later, but I was going through some of the issues and tried this out. I ran into some trouble setting things up (basically docker-compose didn't work for me like the documentation suggested -- I'm not a docker expert at all and am probably doing something wrong). Have you run this before/tried it out? And would you still want this added (I'm fine with either, and demand is clearly low enough that it's a trivial decision).

It's very simple to integrate in (just like Isso), but I want to make sure I can run it and try it out first.

**Comment by mtn** [comment]
Seems to work as expected, so I'm going to go ahead and add it :)

![screen shot 2018-06-17 at 12 15 25 pm](https://user-images.githubusercontent.com/4515110/41510329-3939ffcc-7228-11e8-8ff4-35c7e1994827.png)
