### ISSUE TITLE
Social discussion links

### ISSUE THREAD

**Issue by mtn** [mtn/cocoa-eh-hugo-theme#37]
Hi!

I had an idea that I was thinking about implementing on my site that I thought would be worth suggesting for the theme in general. A number of authors I've read submit many of their posts to news aggregation sites like [Hacker News](news.ycombinator.com) and [Lobste.rs](lobste.rs) for discussion. Some sites do this rather than supporting commenting, while others do and presumably submit posts mainly for increased visibility. I think it'd be cool to support this natively in the theme by allowing users to specify a `hackernews` and `lobsters` content parameter so that a "continue the discussion on Hacker News/Lobsters" link (or button) could be conditionally included at the bottom of the article. Thoughts?

If this was confusing, I can find some concrete examples.

**Comment by mtn** [comment]
I figure I might as well clarify with an image, so here goes (taken from [Anish Athalye's blog](http://www.anishathalye.com/)):

<img width="548" alt="screen shot 2017-06-04 at 7 30 09 pm" src="https://cloud.githubusercontent.com/assets/4515110/26766701/72e6903c-495c-11e7-938b-2cfa4abad0e4.png">

Perhaps something below the title like this? Not too overbearing, and conditionally included for social site links added by the user.

**Comment by fuegoio** [comment]
Hi ! Thank you for the issue !

I think that an awesome idea, it could be really greatly integrated to the theme. It is not too complicated and flexible, I like that !

**Comment by mtn** [comment]
Sounds great! I'll get a pull request going, probably later today or sometime tomorrow.

**Comment by mtn** [comment]
Got bogged down for a few days, but the PR has been made!

**Comment by mtn** [comment]
Implemented in #38.
