### ISSUE TITLE
Error ... general.go:236: theme/partials/li.html is an incomplete or empty template

### ISSUE THREAD

**Issue by ivanbrunodemorais** [mtn/cocoa-eh-hugo-theme#4]
When running Hugo, the articles aren't being rendered and throws this error in the console:

> Posting the full error text:
> ERROR: 2017/01/15 09:50:26 general.go:236: Error while rendering "page blog/passion.md": template: theme/blog/single.html:11:66: executing "theme/blog/single.html" at <.Site.Params.datefor...>: invalid value; expected string
> ERROR: 2017/01/15 09:50:26 general.go:236: Error while rendering "page blog/developpingideas.md": template: theme/blog/single.html:11:66: executing "theme/blog/single.html" at <.Site.Params.datefor...>: invalid value; expected string
> ERROR: 2017/01/15 09:50:26 general.go:236: theme/partials/li.html is an incomplete or empty template

Also, these errors show up on the original Cocoa theme as well, hence blog posts not showing in either version. Might be something with the Hugo version.

**Comment by yeliv** [comment]
Posting the full error text:
ERROR: 2017/01/15 09:50:26 general.go:236: Error while rendering "page blog/passion.md": template: theme/blog/single.html:11:66: executing "theme/blog/single.html" at <.Site.Params.datefor...>: invalid value; expected string
ERROR: 2017/01/15 09:50:26 general.go:236: Error while rendering "page blog/developpingideas.md": template: theme/blog/single.html:11:66: executing "theme/blog/single.html" at <.Site.Params.datefor...>: invalid value; expected string
ERROR: 2017/01/15 09:50:26 general.go:236: theme/partials/li.html is an incomplete or empty template

**Comment by yeliv** [comment]
This errors show on the original Cocoa theme as well, hence blog posts not showing in either version.

**Comment by fuegoio** [comment]
Hi !

Can you verify that your `config.toml` has those params please ?

```
[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
```

Thanks you !

**Comment by ivanbrunodemorais** [comment]
This and checking well the sample config.toml eliminated all errors. Much thanks.
