### ISSUE TITLE
Simpler 404 option

### ISSUE THREAD

**Issue by mtn** [mtn/cocoa-eh-hugo-theme#45]
Hi!

I find the 404 page a bit too "busy" compared to what I'd normally expect. I was thinking it'd be nice to allow for a more subtle option that could maybe be enabled in the config file. For example, I think an nice design is something like this:

<img width="1221" alt="screen shot 2017-07-25 at 8 26 13 pm" src="https://user-images.githubusercontent.com/4515110/28599308-9760b68e-7177-11e7-95b2-f02a93c106b4.png">

And if the relevant parameter isn't specified, the same 404 will persist. This might marginally increase build time, but the resulting pages would be the same size. Even build times would be virtually unchanged, I think, since it's only a single new conditional in a single template.

Thoughts? As always, happy to put in a PR. 🐺

**Comment by fuegoio** [comment]
Hi !

Thanks for your idea, in fact it was in my roadmap (but time ...) to redesign a bit the 404 page to become better integrated with the themes paradigms like minimalism and cleanness. Love your submit ! If you could put a PR it would be awesome.

Maybe don't bother with an attribute and enable it otherwise for everybody, what do you think ?

**Comment by mtn** [comment]
Sure, if you're comfortable dropping the old option, I don't really think there's much reason to keep it around. I'll have a PR in sometime within the next few days!

**Comment by mtn** [comment]
Possibly doing something stupid, but I'm having difficulty testing locally for some reason. Is there any reason you know that the 404 wouldn't be served on localhost? True before and after modifications.

Michael

**Comment by mtn** [comment]
I guess the main relevant issue is [here](https://github.com/gohugoio/hugo/issues/874).

**Comment by mtn** [comment]
Seems like looking at `/404.html` works fine! I'll have the PR done pretty soon :)

**Comment by mtn** [comment]
Handled by #47.
