### ISSUE TITLE
archetypes/default.md contains YAML and TOML syntax

### ISSUE THREAD

**Issue by nancym** [mtn/cocoa-eh-hugo-theme#48]
At the moment `archetypes/default.md` is this:

```
+++
title: "{{ replace .TranslationBaseName "-" " " | title }}"
date: {{ .Date }}
draft: true
meta_img = "/images/image.jpg"
tags = ["tags"]
description = "Desc"
hacker_news_id = ""
lobsters_id = ""
title = "Title"
+++
```

The first 3 settings use YAML syntax and the rest use TOML syntax. This causes an ERROR when `hugo server` is run.

**Comment by mtn** [comment]
@nancym Thanks for pointing this out! Should be resolved once the PR is merged :)
