### ISSUE TITLE
Left-align text for specific page or all pages

### ISSUE THREAD

**Issue by jrosen48** [mtn/cocoa-eh-hugo-theme#50]
Hi, thanks for a great theme. New to Hugo, so I apologize if this is a more general question. Could you suggest how I could align-left text for either a specific page or for all pages?

For example, the references to the tools on [this page](https://jrosen48.github.io/research/) appear strange center-aligned.

**Comment by mtn** [comment]
Now that you mention it, at least for my preference is for left-alignment over the current justify everywhere. It's an easy change, and I can make a PR to enable it as an option. @fuegowolf thoughts?

Left align, for reference:
![screen shot 2017-08-20 at 10 51 31 am](https://user-images.githubusercontent.com/4515110/29495855-94b2d480-8595-11e7-96a1-2c010d228bb5.png)

**Comment by mtn** [comment]
I ended up going ahead and making the PR rather than waiting. If merged, the enable site-wide content left-align, you just need to set `align_left = true` in the site config file (eg. `config.toml`).

**Comment by jrosen48** [comment]
This worked great. Wow, thanks so much!

**Comment by fuegoio** [comment]
Thanks @mtn for the PR ;)
