### ISSUE TITLE
Different sizing of header content

### ISSUE THREAD

**Issue by jrosen48** [mtn/cocoa-eh-hugo-theme#53]
When I navigate from the home page of my site to another page (i.e., the About page), the size of the header section becomes smaller. 

Here, for example, is my homepage: [https://jrosen48.github.io/](https://jrosen48.github.io/)

Here is my About page: [https://jrosen48.github.io/about](https://jrosen48.github.io/about)

Is it possible to fix the header content to be sized identically in each?

Thanks again for a great theme

**Comment by fuegoio** [comment]
Hi ! Thanks for the issue :)

It is a behavior I wanted in the original theme, but we can add an option if you want. Would you like to have the 'small' or the 'big' version on all pages ? Currently, only the menus and homepages are with the big size.

**Comment by jrosen48** [comment]
Wow, thank you for the quick response- the 'small' version on all pages (including homepage), if possible. Thanks again.

**Comment by fuegoio** [comment]
Fixed with fd4a9767aed433d9eb33536d01d598ab253cd179 :)

**Comment by jrosen48** [comment]
Sa-weet! Thanks.

**Comment by jrosen48** [comment]
Thanks again for the help with this - I just made the change, and with `small_banner_logo` set to `true` or `false`, the site appears like this (image is below). Any idea what I'm doing incorrectly?

<img width="1135" alt="screen shot 2017-09-07 at 4 48 23 pm" src="https://user-images.githubusercontent.com/4596214/30184598-9a45035e-93ec-11e7-8659-2f03e215c677.png">

**Comment by fuegoio** [comment]
I don't have the issue on my blog ... What version of hugo are you using ?

**Comment by jrosen48** [comment]
This seemed to do the trick! Was using version `0.18`. Thanks again for a great theme and the great support.
