### ISSUE TITLE
error: wrong number of args for absURL: want 1 got 0

### ISSUE THREAD

**Issue by novelistparty** [mtn/cocoa-eh-hugo-theme#54]
https://github.com/fuegowolf/cocoa-eh-hugo-theme/blob/94e3cef795f2e47c2a868b2534a44cf06d2fd5b5/layouts/partials/header.html#L14

I'm using latest hugo (as of today) and the latest of cocoa-eh-hugo-theme.

```
ERROR 2017/09/08 12:23:44 Error while rendering "page": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:14:88: executing "theme/partials/header.html" at <absURL>: wrong number of args for absURL: want 1 got 0
ERROR 2017/09/08 12:23:44 Error while rendering "page": template: theme/blog/single.html:1:3: executing "theme/blog/single.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:14:88: executing "theme/partials/header.html" at <absURL>: wrong number of args for absURL: want 1 got 0
ERROR 2017/09/08 12:23:44 Error while rendering "section": template: theme/_default/section.html:1:3: executing "theme/_default/section.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:14:88: executing "theme/partials/header.html" at <absURL>: wrong number of args for absURL: want 1 got 0
ERROR 2017/09/08 12:23:44 Error while rendering "home": template: theme/index.html:1:3: executing "theme/index.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:14:88: executing "theme/partials/header.html" at <absURL>: wrong number of args for absURL: want 1 got 0
ERROR 2017/09/08 12:23:44 Error while rendering "section": template: theme/section/blog.html:1:3: executing "theme/section/blog.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:14:88: executing "theme/partials/header.html" at <absURL>: wrong number of args for absURL: want 1 got 0
```

**Comment by mtn** [comment]
Hi @kebno!

What's (most likely) happening is that you don't have a parameter `logofile` set in your config file. For example, from the [example config.toml](https://github.com/fuegowolf/cocoa-eh-hugo-theme/blob/master/exampleSite/config.toml):

```
[params]
...
logofile = "img/logo.png"
...
```

You can fix this by setting that parameter, which should point to the image file that will be rendered as your logo (eg. the wolf in the example site).

I guess we could make this field optional and include a default logofile, but in my mind the current default is saner. @fuegowolf

**Comment by novelistparty** [comment]
that did it! thank you!

**Comment by mtn** [comment]
Sweet! I'm going to leave the issue open for the time being in case @fuegowolf has any thoughts about maybe changing the default.

**Comment by fuegoio** [comment]
I think we should keep the logofile constraint because it is kind of the first goal of this theme. This theme is highly customizable, but the logo is a must for it.

**Comment by dileepsagar** [comment]
i am using timer-hugo and sowing this error.
 link of timer-hugo:https://github.com/themefisher/timer-hugo

ERROR: 2018/11/21 14:21:19 template.go:119: template: theme/partials/header.html:44:57: executing "theme/partials/header.html" at <absURL>: wrong number of args for absURL: want 1 got 0 in theme/partials/header.html
