### ISSUE TITLE
Option to use only fonts from operating system or change to the one with more character sets

### ISSUE THREAD

**Issue by matrixik** [mtn/cocoa-eh-hugo-theme#57]
Hello, thank you for working on this theme.

Would it be possible to have option to use only fonts from user operating system or be able to change them to some other font (e.g. Nexa Bold don't have Polish character sets like `śłć`)?

I'm not a designer and I understand that system fonts are old and looks not so nice but I hate flashing on every website when they load web fonts in the background.

**Comment by matrixik** [comment]
It would also make theme faster (especially on slow connection) and protect readers privacy.

**Comment by mtn** [comment]
Sorry for taking awhile to get to this -- I think it's a great idea.

On a somewhat related note, I'm also thinking it might be a good idea to allow users to choose to load fonts synchronously. One of the less-pleasing aspects of the theme right now, I think, is a flicker effect between when text originally shows up and when fonts are loaded and displayed. Depending on one's priorities, it might be desirable to get rid of this by having them load first at the cost of a slightly slower page load. This won't be a default either, but could also be a nice option.

**Comment by mtn** [comment]
Sorry for the delay, this should now be addressed by #75. Please let me know if something doesn't seem right!

**Comment by matrixik** [comment]
Thank you.

**Comment by niklasfyi** [comment]
If I understand this correctly it is only possible to disabled the fancy fonts. Is it also possible to load a different font?

**Comment by mtn** [comment]
No, it's not unfortunately.
