### ISSUE TITLE
Link to external site as a menu entry

### ISSUE THREAD

**Issue by jrosen48** [mtn/cocoa-eh-hugo-theme#60]
Hi, 

Thank you (once again) for a great theme. Can you recommend how I can add a link to an external site as a menu entry?

For example, let's say I have three pages on my site, "Blog," "About," and "Resources," and I want to add a link to an external site, "My Other Site". Is there a straightforward way to do this?

I tried the approach suggested in [this question](https://github.com/gohugoio/hugo/issues/1774) (adding the link through the `config.toml` file), but that didn't seem to work.

**Comment by mtn** [comment]
Hey @jrosen48! As far as I know, there isn't a straightforward way to do this with the way the theme is currently set up. We can look into adding it though, if @fuegowolf is interested.

In the meanwhile, you can implement the change relatively easily on a fork if you want. The relevant template seems to be in `cocoa-eh-hugo-theme/layouts/partials/header.html`. A simple way to do this would be to just hardcode a `li` within the list linking to your other site. If you want it to be more extensible, you could define a site variable as a param in your `config.toml` and then iterate over it using `range` like in the example. The hugo documentation for `range` and site variables would be pretty helpful.

If you're unfamiliar with web development, the above might be confusing. Happy to explain in more detail if this is the case 🐅

**Comment by Vipermaseg** [comment]
Though I can see why you would like to that, before you embark yourself into forking and reading documentation, let me propose you two ways I think are more elegant.

First, you can do like fuegowolf does in his blog and just have tags with things in it. This is not as straight forward, but it allows for some explanation: https://kodewolf.com/projects/
Second and more limited, even though you probably already noticed, you can configure social media icons at the footer.

**Comment by mtn** [comment]
To do the first (like fuegowolf), you just include a markdown file with a title matching the section title. So not too many hoops to jump through.

**Comment by mtn** [comment]
Closing this issue because I don't think it's associated with any pending new features. Feel free to ping me though, @jrosen48.
