### ISSUE TITLE
Create category-specific RSS feed?

### ISSUE THREAD

**Issue by jrosen48** [mtn/cocoa-eh-hugo-theme#71]
Is there support in the theme for category-specific RSS feeds, i.e. feeds only with posts that are in a specific category? Thanks once again for a great theme. In the case that this would make it easier for others to provide feedback, the source files for my blog with the enhanced Cocoa theme are [here](https://github.com/jrosen48/homepage-source).

**Comment by vsund** [comment]
There are tag-based RSS feeds at `https://your-blog.com/tags/your-tag/index.xml` 👍

**Comment by jrosen48** [comment]
Thanks @vsund!

**Comment by jrosen48** [comment]
Wondering if you could help me - I had some trouble submitting this to a blog syndicator ([RWeekly](https://rweekly.org/)), I think because the feed did not validate, see [here](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fjrosen48.github.io%2Fcategories%2Fr%2Findex.xml). 

There are a number of issues, but the first two say "link must be a full and valid URL: /categories/r/index.xml".

This is for the feed at https://jrosen48.github.io/categories/r/index.xml

**Comment by vsund** [comment]
Hugo itself should be the one who generates this RSS files. I found some (resolved) issues for this, but they *only seem similar* to yours.

I think that you might not set some host variable that tells Hugo what to choose as first part of a URL. Maybe @mtn can help here :)

**Comment by mtn** [comment]
Thanks @vsund -- I'm not too familiar with RSS and actually didn't know Hugo generated ones by tag.

I'll poke at this a bit and open an issue upstream if it seems like something we can't fix here.

**Comment by mtn** [comment]
One of the more annoying things about Hugo (in my opinion) is that it's pretty difficult to tell the value of site variables without literally changing templates. So I don't have a good solution yet, but I figured I might as well share what I noticed so far.

You can find the default RSS template [here](https://gohugo.io/templates/rss/#the-embedded-rss-xml), and the variable that's used the populate the URI field is {{ .Permalinks }}. Not sure where and how that's set though, yet.

**Comment by mtn** [comment]
There's also [this](https://github.com/gohugoio/hugoDocs/issues/285)

**Comment by mtn** [comment]
Closing this since it's been inactive for awhile (including upstream), but if it's still a problem we can look into it more.
