### ISSUE TITLE
change default directory for blog posts?

### ISSUE THREAD

**Issue by jrosen48** [mtn/cocoa-eh-hugo-theme#77]
When I write a post, it automatically appears in the `/content/post` directory, however, I think for this theme, it has to be in the `/content/blog` directory. Is there a way to change the default directory for blog posts so that they (automatically & without having to manually move) appear in the correct (`/content/blog`) directory?

**Comment by mtn** [comment]
You can do this with `hugo new blog/post_name.md`. Are you not including the leading directory? I have always used the explicit syntax, so I wasn't aware that there was a default, but I'll take a look when I'm at my computer.

**Comment by jrosen48** [comment]
Ah, thanks. I am using [Blogdown](https://github.com/rstudio/blogdown) to create the new posts, specifically `blogdown::new_post()`:

```
new_post(title, kind = "default", open = interactive(), 
    author = getOption("blogdown.author"), categories = NULL, 
    tags = NULL, date = Sys.Date(), file = NULL, slug = NULL, 
    subdir = getOption("blogdown.subdir", "post"), ext = getOption("blogdown.ext", 
        ".md"))
```

It looks like if I changed `getOption("blogdown.subdir", "post")` to `getOption("blogdown.subdir", "blog")`, then this might do the trick?

**Comment by mtn** [comment]
That sounds about right :) Let me know how it goes!

**Comment by mtn** [comment]
Closing this for now, but let me know if there were any problems!
