### ISSUE TITLE
resize images added with html src tag

### ISSUE THREAD

**Issue by jrosen48** [mtn/cocoa-eh-hugo-theme#79]
Hi, and thanks (for the 10th time, I think!) for such a great theme. Thank you too for your willingness to support sometimes novice questions!

I am having trouble resizing images added with the html src tag. It seems like it may be due to a theme width which overrides the width attribute. For example, [on this page](https://jrosen48.github.io/research/), I have the following three lines:

```
<img src = "/_media/logos/pdf.png", width = "15", height = "200">

<img src = "/_media/logos/pdf.png", width = "200", height = "200">

<img src = "/_media/logos/pdf.png", height = "200">
```

All three render the same size (on this page [here](https://jrosen48.github.io/research/)) (with a height of `200px`, but what appears to be the maximum width). Any ideas about why this width attribute does not seem to be working and ideas about how I can address it would be super helpful.

**Comment by mtn** [comment]
I believe the issue is just syntactic. I'm not positive (haven't tried it), but I think what's throwing things off is the commas delimiting properties. So I think you're looking for is something like this:

`<img src = "/_media/logos/pdf.png" width = "15" height = "200">`

Alternatively, you can do the styling with CSS:

`<img src="/_media/logos/pdf.png" style="width: 15; height: 200;"/>`

Let me know if it doesn't work!

**Comment by jrosen48** [comment]
problem solved. Thank you!

**Comment by jrosen48** [comment]
Shoot, it worked fine in my HTML previewer, but when I view it either in my browser or upload it to GH Pages, the width issue returns (see [here](https://jrosen48.github.io/research/)). The source for this page is [here](https://github.com/jrosen48/homepage-source/blob/master/content/research.md).

**Comment by mtn** [comment]
I think you want to remove the commas? So:

`<img src = "/_media/logos/pdf.png", width = "40" height = "40">`
becomes
`<img src = "/_media/logos/pdf.png" width = "40" height = "40">`

**Comment by jrosen48** [comment]
Thanks for being so considerate - especially as you can tell I'm a super naive HTML/CSS user).

* I removed *all* the commas (not just those between the width and height attributes)
* I also fixed the anchor tags so they are used correctly

The issue still seems to persist (see page [here](https://jrosen48.github.io/research/) and source [here](https://github.com/jrosen48/homepage-source/edit/master/content/research.md)).

Any ideas?

**Comment by jrosen48** [comment]
One confusing aspect is why it appears to display correctly in my HTML previewer, but not in the browser:

<img width="619" alt="screen shot 2018-01-10 at 11 58 50 pm" src="https://user-images.githubusercontent.com/4596214/34809335-528ce12a-f662-11e7-8ecd-54908c15d33b.png">

**Comment by mtn** [comment]
Of course :) And I'm not an expert either, as you might be able to tell 🎈 

I'm not 100% sure, but there might also be a problem with browser support for the `height` and `width` attributes. How about trying something like:

`<img src="/_media/logos/pdf.png" style="width: 15; height: 200;"/>`

At least in Firefox for me, this seemed to work where `height` and `width` on the image itself did not.

**Comment by jrosen48** [comment]
Couldn't tell! You've done a great job with the theme.

Still not working.

Is it possibly due to this bit of code:

```
{{ if .Site.Params.progressively }}
    {{ $newImage := (print "<figure class=\"progressive\"><img class=\"progressive__img progressive--not-loaded\" data-progressive=\"" .Site.BaseURL "$1/$2\" src=\"" .Site.BaseURL "$1/low/$2\" alt=$3 $4></figure>") }}
    {{ .Content | replaceRE "<img src=\"/(.*)\\/(.*)\" alt=(.*) (.*)>" $newImage | safeHTML }}
{{ else }}
    {{ .Content }}
{{ end }}
```

Someone suggested this [here](https://discourse.gohugo.io/t/odd-behavior-of-width-attribute-for-img-html-tag/9949/2).

**Comment by mtn** [comment]
Oh yea, I was hoping that by just trying a few things we could figure it out, but the next step is to inspect the generated HTML to try and figure out what's going on. I'm a bit busy right now, but should get to it soon. A good place to start is with the html output file (public/{section}/{post}.html or similar) and see what the resulting image tag is. Inspecting it in the browser it seemed unaltered to me, but it would be best to look at the tag itself.

**Comment by mtn** [comment]
So one thing -- the reason the inline CSS (`style=...`) isn't working is you need explicit units. So `1000px` instead of `1000`, for example.

Also, it might just be that I don't understand how img height and width are supposed to be set, but in chrome it looks like the right HTML is being generated. So try adding units?

**Comment by jrosen48** [comment]
Dang, that was it, i.e., I added:

`<img src="/_media/logos/pdf.png" style="width: 30px; height: 30px;"/>`

And it worked great (see [here](https://jrosen48.github.io/publications/)). I'm 🐑-ish by my HTML/CSS knowledge. Thanks v. much.

**Comment by mtn** [comment]
Glad we were able to figure it out! And I really like the little icons 🎈
