### ISSUE TITLE
What does "dateform" and "dateformfull" mean?

### ISSUE THREAD

**Issue by budui** [mtn/cocoa-eh-hugo-theme#84]
It seems that if i change these in Configuration, an error of blog time occurred.

**Comment by mtn** [comment]
They specify the format of the date/time in the theme. For example (from the example `config.toml`)

```
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
```

I believe these have to conform to some standard forms, but I might be wrong. You can see how they are used by just doing a search for the parameter name -- I don't think `dateformfull` is ever explicitly surfaced in the theme, bug `dateform` is.
