### ISSUE TITLE
How customise image size?

### ISSUE THREAD

**Issue by budui** [mtn/cocoa-eh-hugo-theme#85]
Hi, and thanks  for such a great theme. Thank you too for your willingness to support sometimes novice questions!
The picture is displayed normally in the editor(I write *.md file in Typora).
![image](https://user-images.githubusercontent.com/16448529/37632367-ca0d8f8c-2c28-11e8-83cc-f2615fc6b114.png)
But after render by Hugo, these images are zoomed in.
![image](https://user-images.githubusercontent.com/16448529/37632507-7ff65522-2c29-11e8-969e-d22dcd85e99c.png)
If you don't mind page in Chinese, you can visit this [page](https://jinxiapu.com/blog/20180316-%E8%BF%81%E7%A7%BB%E5%8D%9A%E5%AE%A2%E8%87%B3hugoisso/). 
I found something like [this](https://discourse.gohugo.io/t/how-customise-image-size-in-md-files/4529) after Google it.
Do I need to change the CSS file?
(Please forgive me if I do not understand English language in the expression of lack of courtesy)

**Comment by mtn** [comment]
This is similar to issue #79. The solution was to include the image using a html tag like so:

`<img src="/path/to/image.png" style="width: 30px; height: 30px;"/>`

Where you can set the image height and width. Let me know if something doesn't make sense or any of the language was unclear! 🌳

**Comment by mtn** [comment]
I'm going to close this, but let me know if this wasn't resolved for you. ⚖️

**Comment by budui** [comment]
Yes! It works.
![image](https://user-images.githubusercontent.com/16448529/37634054-d1d765ec-2c2f-11e8-8406-cb7c2819cfb2.png)
But when I use style="max-width: 100%;"
![image](https://user-images.githubusercontent.com/16448529/37634146-500534da-2c30-11e8-9a4e-78dd58eb9234.png)
Image zoom in again.
I'm curious why the pictures aren't displayed in their own size?(this picture is 330*300.)
How do I change the CSS file if I want to automatically display the image in its own size? 
What I mean is to change the configuration permanently instead of for changing the style of pictures one by one.

**Comment by mtn** [comment]
Ah, I see what you're saying. The relevant code is [here](https://github.com/mtn/cocoa-eh-hugo-theme/blob/969bd5ca4ed5ba8d7ff3e2c36852e6fd5c97cee4/layouts/partials/css/min769px.css).

Basically, to have symmetry, the width is set to 110% so it overflows the text somewhat. It can definitely look odd at times, but I think it's a pretty reasonable default, and importantly, changing it would change the look of lots of people's themes without warning. Given that you can change the size manually without problem in the cases that you want to, I'm against changing the default.

Another option that shouldn't be too hard is changing it on your theme. If you need help, just let me know. The relevant code is the small css file from the link above. 🎈

**Comment by mtn** [comment]
Completely unrelated, but your logo is awesome! 🐼
