### ISSUE TITLE
A known issue with Mathjax may be need to remedy.

### ISSUE THREAD

**Issue by budui** [mtn/cocoa-eh-hugo-theme#92]
There is a known [issue](https://gohugo.io/content-management/formats/#issues-with-markdown) with hugo when using Mathjax. Official documents show a [way](https://gohugo.io/content-management/formats/#solution) to remedy this problem.
By the way, I try to fix this problem by myself, but I found `<` in mathjax-markdown-solution.html which is showed in official documents has been escaped and mathjax doesn't work. Hope this helps.

**Comment by mtn** [comment]
Sorry, can you elaborate on that example? I remember reading that page, and I think it's not up to date.

**Comment by budui** [comment]
I upload a [test html](https://static.jinxiapu.cn/mathjax_test.html) in my cdn and this the markdown [file](https://static.jinxiapu.cn/test.md)
See file in my markdown editor : 
![screenshot from 2018-03-28 21-27-21](https://user-images.githubusercontent.com/16448529/38031892-e1affaba-32ce-11e8-89de-59f0b04a41d8.png)

**Comment by mtn** [comment]
Hm, sorry for letting this stagnate @Jinxiapu. I think when I get a chance, I'm going to try out KaTeX, which is an alternate rendering system. I've heard good things about it, for awhile. Won't be getting to this for a bit, but wanted to give you an update.

**Comment by mtn** [comment]
There's some discussion about this on [this issue](https://github.com/gohugoio/hugo/issues/1666). I tried out `mmark`, and it works as expected:

![screen shot 2018-06-16 at 12 15 46 pm](https://user-images.githubusercontent.com/4515110/41500841-0b22444c-715f-11e8-90c1-7777de8df7c4.png)

with basically the same input file. For reference, you can find that input file [here](https://gist.github.com/ac0092763e2843e2c06a05c241c98049). Switching to `.md` immediately breaks things. In all cases, it seems like you can use `$$` as your delimiter -- for non-inline, just don't put other text on the line.

Given how much easier working with `mmark` seems to be, I'm going to leave things the way they are and consider `mmark` the supported way to create files that must render latex. I'm happy to discuss if you disagree, but it's probably better for everyone's sanity to do it this way.

Lastly, I might try out KaTeX in the future, but am putting that off for now. If anyone desperately wants that, I'll make it a higher priority.

**Comment by mtn** [comment]
And thank you for making the issue!
